// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbNhL+Kzu8zrSd06utOo2+3LiW27BnOz6/tJOLfA5ELiUkIMAAoGXV4/9+swBJ",
	"iRKlOL2LLx/um0kC2BfsPvvsyg9BpNJMSZTWBMOHIGOapWhRu6dQGstkhGF8zuyM3sRoIs0zy5UMhsG1",
	"5B9zBB6jtDzhqEElYGcIvNgYtAK8Z2kmMBgG/b19HPxw8KKNP76ctPt78X6bDX44aA/2Dg76g/6LQa/X",
	"C1oBp5MzktcKJEtpJ6/0CFqBxo851xgHQ6tzbAUmmmHKSLmU3Z+gnJKmB/utIOWyfOy36ESLms7+11vW",
	"/qPXfnnzXfFH++ah1zroP5bvv//bN0ErsIuMZBuruZwGj4+PpSjnmmOtld70yMXPR/Dix94LILcKzqQF",
	"pJWg0WRKGvJIplWG2nI0fr9lXGye9CpPmWxrZDGbCAS8zwSTjD6CyTDiCY/AKrAzbkBFUa41rjv8aobw",
	"LbnwW0g4ihi4gdJ7MMktzJkBqSxkWt3xGONNq1uV7xtu/yIEjQk6wZAo7ZWptPOGb9Gt676a7hODIlE6",
	"ZTYYBrnm7Upok77GMpubBn9eXZ2D/wiRimvaDHq96iQuLU5R01GWW9Fg9+VMaQuz+v2YPE2ZXpQJkGk1",
	"EZjWTA7lHRM8hlBmuW1S3b/Y7eYi1xZcTp0g72S3c1XWzNrMDLvdOEo7xdtOpNLS69yr0uaFKk917+Nq",
	"+r0NCrHeTzfVajV5j5Eli14hE03A4d+X12G4nAq0SlKWqFxHm1mSNeLPEZNK8ogJoO+l71cOWXGI14T0",
	"Z/FrKRYlfDw9gFZ1bjh70eiuuktawX2bYdauVPSmETAZcmih5U0ryESumagOJ4GVmyrk43KaC6ZXzSs1",
	"QH3HIywSW3coDrjqFstIsUu/4mqRYbg1xX/OhYDiLBdkFbJXXgaNmUaD0jpw2ri5SCOzeGt52nD+FU/R",
	"WJZmMJ+hrJUOB04J18aCPyJejdOYWWy7M59wozEKJIG32652VCwoA5KwLKYsIKAsd5sOHE7ITveZRZbf",
	"4ViW6poOXB69Oh5dnxyPgMuYR8yiqVvEDXzMMcfYnRAJZDLPOmP582G4uav4DDNmAO8jxBhjSNk9T/MU",
	"NFrN0XTG8vz4bBSe/XJ7fvH6t3B0fLFD9pxxS7BBwrk1Y1lGB9WRCUYqRShCGSaYKL1UwhUOEhl3xnTF",
	"KPOU4rUyOWgF3oqgFayrROH8yTvi8VPohS8yCEXwAkUvhP8B2fjvUoZPWtkMYxdlKjkUW5pbM6jIwjad",
	"2S6v9anl89OKFaFw6xnXuoZnLMWV0uaW1rT7kE/wjmvb7u/tN1blDCM6lsUxpzOZOF9BCa/UWpUtrrik",
	"E576JEoINacoVrLSyORZprTFuAZVY1nQNfjut9PLDKMWHClpGZeo/eOIWTZhBv2T0nAkcmP91+99oG9U",
	"tG0QcumRYxf/vTg+HL15ymXkWfznIVMwY8Gf8GcRc63K12OjuMubzy1tjfFrug/ln7c8fqwVvsYNQa3q",
	"bVuyuwg279pSE0+4sZuXcM6mXJKHQXBj6dYrizYK4PILPVhM3R/faEyCYfCX7rL/6hbx2m0qzUsqwbRm",
	"C3qWeG9vMzbFW6s+oGwIFXrtMNOD911JGmkn0E7SXKPJha0zGlz8mv3zKDwI3x8vTveue2dXb/ZPfr8e",
	"vP49tKdXv344XfRnZ6PrvZOrfyzO3r+5Pxsd75+NDuenR7++fAINcs0Ul4lyBIGSMiInP65jwOjoFC7P",
	"ocLHUybZFFOqwYfnIbThiJgB4QKTVByrryqpSkSNtVDFvKImhbZzMpaWm+01BRKh5sAM0QEuMQbuUm4s",
	"STWUM1rjJNKdK8OEhw3BI6Rmb/hQtrCHGYtmCHsdguNcixWOPp/PO8x97ig97RZ7TfckPDo+uzxu73V6",
	"nZlNxUpLUqHjeRHb312ef7/NT0EruENtvEvv+kxkM9anw1SGkmU8GAb7nV5nEPj65MKzZIrDh2CKdisZ",
	"jmYYfXARtvuqAidMu7sK42AY/IL21ZKR+9bYCd7r9cqgQOkEsywTBfx33xvl4nzZ8+/Ko1cl290IrNd/",
	"d1FZNG1r9lAAs2mNj9PiZtwwW110gTbX0gCrMKKRSBuYc+pdMl8WIeHCosubdZ8RFIWrMLMyq3m7wdzd",
	"MZXIlaLt5isfc9SL5YBl5fPStRtZvEXG0pLJombjFmHFkttiyWcIDBNwBQuMSmzbEXOXkqV8psmvkcjj",
	"KlNLeBtLJpScGh5jwd1XQAFGmDBaRUw4YcKgT+NG7WdqfluIrmkf+zOCoTuggryJUkSim8w5Ldi8zNOJ",
	"n50VykKG2uHzFh1Sdu+B3/A/sFmJfq/n2C0JKJ+4LJ42hx2byi2LR+aLnW/uGqNnWYN2XefNF0z1bZW7",
	"Ifcv8yhCY5JcQJVfhIaDneoUA52/fp5afkrYoMRPLHajODTWd6jFtT2X/GuJ9xlGlD5YrFmFQ/IdsG29",
	"v1lByIo/3VAXoZrIkivSCAwkzpdcVSXAasd3xvJ1AYJiUdD+BTCIBEdp28wYPqUKHI7G8o4zl9zvePwO",
	"XDRChYYdCJPaVLPlKzbJQg1zLgRMUdLNIzAJ4cgnex1svdIrreVOtC0Vh3DkUqbRbVuyh9dh5MsOsW88",
	"tUdjf1Lx4kumn4+6+rD+cQMB+l9ehbUSUsZfOVR67swvp8B+9OqkD55P+pmykKhcFna/fD7JR0omgkcW",
	"2lVChCNggnrRBRXr3LguZ7C393xK/UZX4TsIvI8wK2vB14bHJYTKHfjZDMrbieuy9Q7jR4/aRGqaiGyq",
	"7mrCO/D7DCW8K2ek74CbgpmV01JIGBe59qRsLDVGShesjFVjRTcNdb2bZ2oOmKhZdcTZ+ELdAdexcTOW",
	"ucEY4pywDDTOFrEupkJCzR13Y3eKxzARKvrgZ0QV8fVuNU1Q76a/O6C+6UKXS7prP5JuMinnqx3eWY6a",
	"yYK6c/yAGVns2SE5hgxj0tvTgetdLtnOYkuRn8dgNxncYDNcKoQt+bmpCJdY/M/gNhy5MaHgJeQPnlOH",
	"wiNyFX2/NozxabCa5ttoXmO7+wvaGj5NFsCtgdzP8MNR0wjgy+XcUzpFn07F6yLFBr1BZyyfpR185nbo",
	"q22F/p+hT83Q9RRbGyltIQB0hGt9fGb52WOXZby7nAXeVFs3ftdonulV4WI2/0unIR1r48KmveUP0zeP",
	"/w4AAP//oN60hpIkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
